# Generated by Django 4.2.13 on 2024-07-28 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="first_name",
            new_name="firstname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="last_name",
            new_name="lastname",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="contact_phone",
            new_name="phonenumber",
        ),
    ]
