# Generated by Django 4.2.13 on 2024-08-03 15:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0039_rename_first_name_order_firstname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="fix_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Фиксированная цена",
            ),
            preserve_default=False,
        ),
    ]
