# Generated by Django 4.2.13 on 2024-08-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0041_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Необработанный"),
                    ("preparing", "Готовится"),
                    ("delivering", "В доставке"),
                    ("done", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                db_index=True,
                default="new",
                max_length=255,
            ),
        ),
    ]
