# Generated by Django 4.2.13 on 2024-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0042_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True),
        ),
    ]
