# Generated by Django 4.2.13 on 2024-08-17 11:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0043_order_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="called_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Время звонка с клиентом",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivered_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                default=None,
                null=True,
                verbose_name="Время когда доставлен заказ",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="registrated_at",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Дата создания заказа",
            ),
        ),
    ]
