# Generated by Django 4.2.13 on 2024-08-17 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0044_order_called_at_order_delivered_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_type",
            field=models.CharField(
                choices=[("cash", "Наличностью"), ("card", "Электронно")],
                db_index=True,
                default="cash",
                max_length=255,
                verbose_name="Тип оплаты",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="comment",
            field=models.TextField(blank=True, verbose_name="Комментарий"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Необработанный"),
                    ("preparing", "Готовится"),
                    ("delivering", "В доставке"),
                    ("done", "Доставлен"),
                    ("canceled", "Отменен"),
                ],
                db_index=True,
                default="new",
                max_length=255,
                verbose_name="Статус заказа",
            ),
        ),
    ]
